version: '3'

services:
  nest_api_dispach_control_system:
    container_name: 'nest_api_dispach_control_system'
    depends_on:
      - database_sce
    build: .
    command: "yarn start:dev"
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/api
    networks:
     - nw_horaextra

  database_sce:
    container_name: 'database_sce'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
#     ports:
#       - ${PORT_DATABASE}:5432
    restart: unless-stopped
    networks:
     - nw_api_sce
networks: 
 nw_api_sce:
    driver: bridge
    name: nw_api_sce
